<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "js_event"
 *
 * Auto generated by Extension Builder 2015-07-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Event Management',
	'description' => 'Event Management',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0 - 6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);