<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "company_management"
 *
 * Auto generated by Extension Builder 2015-01-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Company Management',
	'description' => 'This is the extension for company management system of states.',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);