<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fluxtemplate"
 *
 * Auto generated by Extension Builder 2015-01-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fluid - Flux template',
	'description' => 'Default template for site',
	'category' => 'misc',
	'author' => 'Martin Galler, Andreas Predl, Ghanshyam Gohel',
	'author_email' => 'martin.galler@weboffice.co.at, andreas.predl@weboffice.co.at',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.2.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);